# Minimal Verdaccio config: proxy/cache for registry.npmjs.org
storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 10
    timeout: 60s
    cache: true

packages:
  '**':
    access: $all
    publish: $anonymous
    proxy: npmjs

middlewares:
  audit:
    enabled: false

logs:
  - { type: stdout, format: pretty, level: warn }

web:
  enable: false
