---
local:
  hosts:
    localhost:
      ansible_connection: local

brix_pc:
  hosts:
    brix-pc:
      ansible_host: "{{ brix_pc_host | default('192.168.150.90') }}"
      ansible_user: "{{ brix_pc_user | default('ysamohvalov') }}"
